networks:
  access-bridge:
    driver: bridge
  application-bridge:
    driver: bridge
services:
  ejbca-database:
    container_name: ejbca-database
    image: "library/mariadb:latest"
    networks:
      - application-bridge
    environment:
      - MYSQL_ROOT_PASSWORD=Cyblore123!
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=ejbca
      - MYSQL_PASSWORD=ejbca
    volumes:
      - ./datadbdir:/var/lib/mysql:rw
  ejbca-node1:
    hostname: ejbca-node1
    container_name: ejbca
    image: keyfactor/ejbca-ce:latest
    depends_on:
      - ejbca-database
    networks:
      - access-bridge
      - application-bridge
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://ejbca-database:3306/ejbca?characterEncoding=UTF-8
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=simple
      - EJBCA_CLI_INSTALL_NOHTTPS=true
    ports:
      - "80:8080"
      - "443:8443"

  mssql-server:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - application-bridge
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Cyblore123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./sqldata:/var/opt/mssql
